### ISSUE TITLE
Wanted script for extracting features

### ISSUE THREAD

**Issue by prajwalgatti** [AndresPMD/StacMR#2]
Hey @AndresPMD

I couldn't find the script in the repo for extracting image and scene text features. Could you please share it?

Thanks

**Comment by AndresPMD** [comment]
Hello @prajwalgatti 

Thanks for your interest in our work.

In order to extract the image features, I used the code from 

https://github.com/furkanbiten/bottomup_topdown_features

However, there are many other implementations to extract the features from visual regions.

In order to extract the OCR tokens, I employed my own script that used Google OCR. You can refer into their documentation to use it. 
https://cloud.google.com/vision/docs/ocr

I hope you find this information useful.

**Comment by prajwalgatti** [comment]
Thanks, Andres for the reply, that was helpful.

Could you also share what parameters you used in the bottom up attention's image extraction? (like confidence threshold, nms, which pre-trained model, etc)

**Comment by AndresPMD** [comment]
@prajwalgatti 
I edited my previous comment with the link used to extract the features. In that repository, you can find all the parameters required.

**Comment by prajwalgatti** [comment]
Thanks for the help Andres :)
